<?xml version="1.0" encoding="utf-8"?><Database Name="POLLYCAFE" Class="PollyCafeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-PR87JTFE\SQLEXPRESS;Initial Catalog=POLLYCAFE;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="GUI_Pollycaffe.Properties.Settings" SettingsPropertyName="POLLYCAFEConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietPhieu" Member="ChiTietPhieus">
    <Type Name="ChiTietPhieu">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaPhieu" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="MaSanPham" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuBanHang_ChiTietPhieu" Member="PhieuBanHang" ThisKey="MaPhieu" OtherKey="MaPhieu" Type="PhieuBanHang" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietPhieu" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheLuuDong" Member="TheLuuDongs">
    <Type Name="TheLuuDong">
      <Column Name="MaThe" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChuSoHuu" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TheLuuDong_PhieuBanHang" Member="PhieuBanHangs" ThisKey="MaThe" OtherKey="MaThe" Type="PhieuBanHang" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiSanPham" Member="LoaiSanPhams">
    <Type Name="LoaiSanPham">
      <Column Name="MaLoai" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="LoaiSanPham_SanPham" Member="SanPhams" ThisKey="MaLoai" OtherKey="MaLoai" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNhanVien" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VaiTro" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_PhieuBanHang" Member="PhieuBanHangs" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="PhieuBanHang" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuBanHang" Member="PhieuBanHangs">
    <Type Name="PhieuBanHang">
      <Column Name="MaPhieu" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaThe" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PhieuBanHang_ChiTietPhieu" Member="ChiTietPhieus" ThisKey="MaPhieu" OtherKey="MaPhieu" Type="ChiTietPhieu" />
      <Association Name="NhanVien_PhieuBanHang" Member="NhanVien" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="TheLuuDong_PhieuBanHang" Member="TheLuuDong" ThisKey="MaThe" OtherKey="MaThe" Type="TheLuuDong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSanPham" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoai" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="SanPham_ChiTietPhieu" Member="ChiTietPhieus" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="ChiTietPhieu" />
      <Association Name="LoaiSanPham_SanPham" Member="LoaiSanPham" ThisKey="MaLoai" OtherKey="MaLoai" Type="LoaiSanPham" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>